import { Employee } from 'src/employee/schema/employee.schema';

const data: Employee[] = [
  {
    firstName: 'Henri',
    lastName: 'Rodriguez',
    email: 'Darrin_Rippin@gmail.com',
    phoneNumber: '+94771277218',
    gender: 'M',
    photo: 'https://randomuser.me/api/portraits/men/92.jpg',
  },
  {
    firstName: 'Lindsay',
    lastName: 'Herman',
    email: 'Ewald.Kunde@gmail.com',
    phoneNumber: '+94771274218',
    gender: 'F',
    photo: 'https://randomuser.me/api/portraits/men/30.jpg',
  },
  {
    firstName: 'Gerda',
    lastName: 'Trantow',
    email: 'Mauricio.Stehr@yahoo.com',
    phoneNumber: '+94771277681',
    gender: 'M',
    photo: 'https://randomuser.me/api/portraits/men/85.jpg',
  },
  {
    firstName: 'Skye',
    lastName: 'Rolfson',
    email: 'Angelita_Simonis@hotmail.com',
    phoneNumber: '+94771277689',
    gender: 'F',
    photo: 'https://randomuser.me/api/portraits/men/75.jpg',
  },
  {
    firstName: 'Simeon',
    lastName: 'Russel',
    email: 'Fabiola_Heidenreich@yahoo.com',
    phoneNumber: '+94771277682',
    gender: 'M',
    photo: 'https://randomuser.me/api/portraits/men/81.jpg',
  },
  {
    firstName: 'Kenyon',
    lastName: 'Fahey',
    email: 'Lia_Purdy@hotmail.com',
    phoneNumber: '+94771277683',
    gender: 'F',
    photo: 'https://randomuser.me/api/portraits/men/31.jpg',
  },
  {
    firstName: 'Toni',
    lastName: 'Boyle',
    email: 'Vivien92@yahoo.com',
    phoneNumber: '+94771277684',
    gender: 'M',
    photo: 'https://randomuser.me/api/portraits/men/88.jpg',
  },
  {
    firstName: 'Fredy',
    lastName: 'Fritsch',
    email: 'Christopher_Wisozk37@yahoo.com',
    phoneNumber: '+94771277685',
    gender: 'M',
    photo: 'https://randomuser.me/api/portraits/men/61.jpg',
  },
  {
    firstName: 'Elvis',
    lastName: 'Konopelski',
    email: 'Mavis27@gmail.com',
    phoneNumber: '+94771277686',
    gender: 'M',
    photo: 'https://randomuser.me/api/portraits/men/66.jpg',
  },
  {
    firstName: 'Lulu',
    lastName: 'Reinger',
    email: 'Melany_Rau70@gmail.com',
    phoneNumber: '+94771277687',
    gender: 'F',
    photo: 'https://randomuser.me/api/portraits/men/32.jpg',
  },
  {
    firstName: 'Kelton',
    lastName: 'Rau',
    email: 'Patrick_Ratke@gmail.com',
    phoneNumber: '+94771277688',
    gender: 'F',
    photo: 'https://randomuser.me/api/portraits/men/71.jpg',
  },
  {
    firstName: 'Adonis',
    lastName: 'Schuppe',
    email: 'Johann.Orn52@hotmail.com',
    phoneNumber: '+94771277618',
    gender: 'M',
    photo: 'https://randomuser.me/api/portraits/men/36.jpg',
  },
];

export default data;
